name: lab5-tests

on:
  push:
  pull_request:

jobs:
  final-project-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r starter-project/llm-sec-final-project-starter/requirements.txt
      - name: Run unit tests
        env:
          GEMINI_API_KEY: dummy
          MODEL_ID: gemini-2.5-flash
        run: |
          cd starter-project/llm-sec-final-project-starter
          python -m unittest discover tests
